name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: run_one_test
        type: choice
        options:
          - run_all_tests
          - run_one_test

env:
  OWNER: "curiousdenis"
  REPO: "docker_tests"

permissions:
  id-token: write
  pages: write
  contents: read

jobs:

  download_history:
    runs-on: ubuntu-latest
    env:
      FETCH: "allure-results"
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: actions/checkout@v4
      - run: pip install requests
      - run: python fetch_data_git.py ${{ secrets.TOKEN }} ${{ env.OWNER }} ${{ env.REPO }} ${{ env.FETCH }}
      - name: Download latest artifact as a zip file
        if: ${{ env.DOWNLOAD_LINK == 'EMPTY' }}
        run: ${{ env.DOWNLOAD_LINK }} -o artifacts.zip
      - name: Create an empty zip file when there is no artifacts
        if: ${{ !env.DOWNLOAD_LINK == 'EMPTY' }}
        run: zip -r artifacts.zip
      - run: mkdir allure-results && unzip artifacts.zip -d allure-results
      - uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  test:
    needs: download_history
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.49.1-noble
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - uses: actions/download-artifact@v4
      - name: run_all_tests
        if: "github.event.inputs.deployment_target == 'run_all_tests'"
        run: pytest tests.py --alluredir=allure-results
        continue-on-error: true
      - name: run_one_test
        if: "github.event.inputs.deployment_target == 'run_one_test'"
        run: pytest tests.py -m run_one_test --alluredir=allure-results
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  report:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: homebrew/brew:latest
      options: --user root
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - run: brew install allure
      - uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site

  publish:
    runs-on: ubuntu-latest
    needs: report
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - uses: actions/deploy-pages@v4
