name: Automated tests
on:
    push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.13'
          - uses: browser-actions/setup-chrome@v1
          - uses: pip install -r requirements.txt
          - run: pytest tests.py