name: Automated tests
on:
    push
jobs:
    test:
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/playwright/python:v1.49.1-noble AS pytest_run
        steps:
          - run: pip install -r requirements.txt
          - run: pytest tests.py