name: Automated tests
on:
    workflow_dispatch:
      inputs:
        deployment_target:
          description: Choose target
          required: true
          default: run_one_test
          type: choice
          options:
            - run_all_tests
            - run_one_test
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.49.1-noble
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - name: run_all_tests
        if: "github.event.inputs.deployment_target == 'run_all_tests'"
        run: pytest tests.py --alluredir=allure-results
      - name: run_one_test
        if: "github.event.inputs.deployment_target == 'run_one_test'"
        run: pytest tests.py -m run_one_test --alluredir=allure-results
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: allure-results

  report:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: homebrew/brew:latest
    steps:
      - run: pip install allure
      - uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o allure-report
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: allure-report

  publish:
    runs-on: ubuntu-latest
    needs: report
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
      - uses: actions/deploy-pages@v4
